Feat/profile page/side columns
weech22/twitter-demo-frontend pull request #2
Opened 2018-06-20 08:00 UTC by weech22

https://confident-hugle-4730c4.netlify.com

2018-06-20 21:47 UTC, imevro requested changes

2018-06-20 21:47 UTC, evgenyrodionov commented on src/Copyright/index.js
> +  letter-spacing: -0.4px;
да нет же, не нужно это говно тащить

2018-06-20 21:47 UTC, evgenyrodionov commented on src/FamiliarFollowers/index.js
> +import avatar2 from "./avatars/2.jpg";
это не имеет отношения к интерфейсу, все контентные изображения нужно кидать в паблик

2018-06-20 22:16 UTC, weech22 commented on src/Copyright/index.js
> +  letter-spacing: -0.4px;
Иногда бывает, что без этого не влезает, и получаются расхождения с макетом.

2018-06-22 20:50 UTC, imevro approved these changes

2018-06-22 20:50 UTC, merged